### ISSUE TITLE
Location results do not honor ticket permissions

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#107]
When you do a location search, the location results include a count of tickets.  This count does not reflect the tickets that are permitted to be displayed.

We need to make the ticket count on the location search results display the correct number of tickets that are allowed to be displayed.

**Comment by inghamn** [comment]
Even though you might not be allowed to see them all, the ticket count is accurate.

**Comment by rbdietz** [comment]
Are you sure this is what we want?
