### ISSUE TITLE
Ticket search date range end date wierdness

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#164]
When searching from the main page for cases within a specific date range (say all pothole cases in the month of January 2014), the “end” date isn’t included in the filtered results.  It looks like the “end” date starts as 12:00am… does that makes sense?  Anyway, my recommendation was for them to use the first of each month (2014-01-01 thru 2014-02-01), but they asked if it was possible to modify the search filter to include the “end” date on the results.

**Comment by rbdietz** [comment]
May be mooted by browsers and HTML5 date field.

**Comment by inghamn** [comment]
We now add the time portion to the start and end dates from the search form.  We treat it as midnight on the start date and 11:59pm on the end date.

So, putting the same date in both start and end date on the search form returns tickets that were added from midnight to 11:59pm on that date.

Fixed in datefix merge: 79dca9d2b3b723cf75d80f4e4f6925ebcab26479
