### ISSUE TITLE
Add SLA to the search filters

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#182]
We want to be able to search on tickets that have been open past their SLA time.

So, if a category is marked as 2 days, we want to be able to search for all tickets that are overdue.

**Comment by inghamn** [comment]
Solr allows queries that include functions.  However, there are no date functions.  So, we can do some basic math, but that's about it.

We should store the dates as unix timestamps.  That way, we can calculate whether a ticket is overdue with just basic integer subtraction.

**Comment by inghamn** [comment]
After reading through the SOLR documentation, we should be able to use real date fields in the index.  In fact, we are already storing enteredDate as a Date.

The solr dates get evaulated as unix timestamps in milliseconds.  SOLR 4 even includes an IF statement we can use.

We still need to figure out what to do about SLA days. 

SLA days are per category.  Doing a search for all tickets that are overdue involves SOLR looking up SLA days for eack ticket.  This field is currently not in SOLR.  In fact, we probably don't want it inside of SOLR, since changing the value on a category would require reindexing all the tickets for that category.

**Comment by inghamn** [comment]
Really we're just trying to find a way to provide data about the SLA status of tickets.

We might need to put this into reports, instead of trying to work it into search.

The big things we want to know are:
What categories have SLA on them?
What's the average number of days tickets spend open?
What tickets are overdue?

**Comment by rbdietz** [comment]
I think we want it in Search, so folks can take direct action on the
overdue cases.
Also we will be adding SLAs to most categories that don't have them.

On Fri, Jan 9, 2015 at 1:18 PM, Cliff Ingham <notifications@github.com>
wrote:

> Really we're just trying to find a way to provide data about the SLA
> status of tickets.
>
> We might need to put this into reports, instead of trying to work it into
> search.
>
> The big things we want to know are:
> What categories have SLA on them?
> What's the average number of days tickets spend open?
> What tickets are overdue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/uReport/issues/182#issuecomment-69374940>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov

**Comment by inghamn** [comment]
I'll plan on implementing it such that we reindex SOLR whenever a category is SLA is changed.  We'll see how that goes.
