### ISSUE TITLE
Allow for categories to be "Most Popular"

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#196]
From a uReport feedback request:

> I wanted to report a pothole, so I first looked under "Streets", but there was no place there for potholes. I then looked under "Hazards", but there wasn't a place there either. I finally found it under "Most Popular". It's OK to put things under "Most Popular", but they also should be under the category that they logically fit under.

Right now, categories are in one, and only one, group.  We should allow for categories to be in multiple groups.

**Comment by charlesbrandt** [comment]
What is involved with this?

**Comment by inghamn** [comment]
The categories table has a categoryGroup_id field.  I would need to create a new category_categoryGroups rewrite the Category models to handle saving an array of group_ids for each Category.  

I've done this work many times with various applications.  It take a couple hours of work to rewrite the code (including database migration stuff)

**Comment by inghamn** [comment]
Open311 only supports a single group per category.  We need to build a way to designate one of the groups as the Open311 group for each category.

**Comment by rbdietz** [comment]
The real issue here is that we want to be able to place some reports in a
"most popular" category IN ADDITION to their topical category. Maybe just
generate "most popular" procedurally or allow us to "star"/flag a report.

Another option is to essentially create alias reports.

**Comment by inghamn** [comment]
So, it's not that we want to have categories to be organized into many arbitrary groups.  Rather, we just want to be able to have Open311 clients show some "Most Popular" categories.

We need to deviate a little from Open311 and add an additional property to our Open311 Service List.  We should mark services as "featured" or something.  That way, we can write our own Open311 clients to look for this custom property in the service list, and pull out the services we've flagged.

uReport just needs to add an additional field for this "Most Popular" or "Featured" flag.
