### ISSUE TITLE
A new category... 

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#200]
for Crow Droppings (exact text TBD). This category should be set to close automatically after automated email response has been sent.

**Comment by rbdietz** [comment]
This is a configuration not coding issue.  Also, not yet confirmed by PTB.

On Tue, Oct 13, 2015 at 3:37 PM, Charles Brandt <notifications@github.com>
wrote:

> for Crow Droppings (exact text TBD). This category should be set to close
> automatically after automated email response has been sent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/uReport/issues/200>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
