### ISSUE TITLE
Categories should have a reply-to email address

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#202]
When we send out notifications, we want to make sure that email replies to the notification are sent to the best place we can.

If we allow for a reply-to address to be set on the Catgeory, we can use that address when we send notifications.

**Comment by rbdietz** [comment]
This should be optional on a per category basis.  Some mailings should be
from a no-reply email address.

On Thu, Oct 15, 2015 at 12:23 PM, Cliff Ingham <notifications@github.com>
wrote:

> When we send out notifications, we want to make sure that email replies to
> the notification are sent to the best place we can.
>
> If we allow for a reply-to address to be set on the Catgeory, we can use
> that address when we send notifications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/uReport/issues/202>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov

**Comment by charlesbrandt** [comment]
By having a configuration in the section where auto-responses are set, we can configure this on a case by case basis. Currently, without a configuration option, all emails will be sent from our default system address. This has the potential of creating a situation where many automated emails are sent out and any replies would need to be manually routed by ITS. Having a setting for this should prevent this.
