### ISSUE TITLE
Notifications should include a link to the ticket

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#203]

**Comment by rbdietz** [comment]
This should be optional on a per category basis.

On Thu, Oct 15, 2015 at 12:24 PM, Cliff Ingham <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/City-of-Bloomington/uReport/issues/203>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov

**Comment by rbdietz** [comment]
This needs to be optional.  We don't want a ticket link sent in a lot of cases.

**Comment by inghamn** [comment]
Links are not included if tickets of that category are not viewable by the person receiving the notification.

**Comment by rbdietz** [comment]
That's not the point.  Confer with Charles.

**Comment by charlesbrandt** [comment]
Links in emails have been commented out for now.
