### ISSUE TITLE
Admin Guide enhancement

### ISSUE THREAD

**Issue by milovanderlinden** [City-of-Bloomington/uReport#205]
In the Admin Guide (wiki) Install section; there is a section Verify Installation. When you follow the guide, this section is positioned wrong. When you haven't correctly set up SOLR, the application will not succesfully reach the <your-host>/tickets page.

I believe this section should move down, and a small reference to install SOLR should be placed beforehand.

**Comment by inghamn** [comment]
The Admin guide should be deleted or rewritten.  We haven't touched it since 2012, and it was out of date, then.
