### ISSUE TITLE
Can't parse point in solr5

### ISSUE THREAD

**Issue by milovanderlinden** [City-of-Bloomington/uReport#218]
I am using solr 5 in my setup and when the application issues a request with a bounding box like:

[http://localhost/crm/tickets?bbox=31.759402397310296,35.21424558715819,31.77399702718368,35.25235441284178;zoom=15](http://localhost/crm/tickets?bbox=31.759402397310296,35.21424558715819,31.77399702718368,35.25235441284178;zoom=15)

This results in a solr error:

` ` `
solr-1 | 2016-01-22T08:16:51.248112957Z 338303333 INFO  (qtp5592464-15) [   x:open311-ehv] o.a.s.c.S.Request [open311-ehv] webapp=/solr path=/select params={q=*:*&json.nl=map&stats=true&stats.facet=cluster_id_3&start=0&sort=enteredDate+desc&fq=displayPermissionLevel:anonymous&fq=coordinates:[31.75575373984195,35.20471838073729+TO+31.777645684652025,35.26188161926268]&rows=0&wt=json&stats.field=latitude&stats.field=longitude} hits=0 status=0 QTime=343 
solr-1 | 2016-01-22T08:16:52.066959778Z 338304121 ERROR (qtp5592464-17) [   x:open311-ehv] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Can't parse point '31.77399702718368,35.25235441284178;zoom=15' because: java.lang.NumberFormatException: For input string: "35.25235441284178;zoom=15"
` ` `

I would like to strip the zoom=15 before sending the request from the application to solr, but don't know if this is on purpose in the setup with solr 4.

@inghamn Can you advice if it can be removed or if it should stay?

**Comment by milovanderlinden** [comment]
I can confirm that this request:

[http://localhost/crm/tickets?bbox=31.759402397310296,35.21424558715819,31.77399702718368,35.25235441284178](http://localhost/crm/tickets?bbox=31.759402397310296,35.21424558715819,31.77399702718368,35.25235441284178)

is handled properly.

**Comment by inghamn** [comment]
I can confirm the zoom=15 is not needed for Solr requests.  It is probably an error on our part in converting user-provided URL parameters into Solr requests.

**Comment by milovanderlinden** [comment]
Ok, I will provide a fix that will remove zoom= from the query that is sent to Solr. Thanks for the advice!

**Comment by milovanderlinden** [comment]
I found the cause of this problem. In urlParsing.js there is a replaceParam function. This function contains:

```javascript
if (href.indexOf('?') === -1) {
  href += '?' + key + '=' + value;
} else {
  href += ';' + key + '=' + value;
}
```

In the else part of the function, a ;  is placed. If I replace that with a &, the faulty query from previous comments is processed correctly.

**Comment by milovanderlinden** [comment]
I checked the sources and this replaceParam is only used for bbox and zoom, not for any of the other URL constructors. Pull request on the way.

**Comment by inghamn** [comment]
Awesome.  Nice catch.  You, sir, are a wizard!

Someday I need to get a better generalized way of handling url parsing.  Especially when we use a different parameter separator than '&'.
