### ISSUE TITLE
validator metadata should be array

### ISSUE THREAD

**Issue by milovanderlinden** [City-of-Bloomington/uReport#222]
http://validate.open311.org/validate?schema=georeport-v2%2Fservices.json&output=browser&datajson_url=http%3A%2F%2Feindhoven.meldloket.nl%2Fcrm%2Fopen311%2Fv2%2Fservices.json&qa=true

**Comment by inghamn** [comment]
Our system does not actually use keywords, so this had gone unnoticed for a long time.
