### ISSUE TITLE
Sort By -> Category does not work

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#260]
When a search contains cases with multiple categories, sort by category does not seem to group by category

**Comment by charlesbrandt** [comment]
This only seems to be the case with search results from a keyword search.

**Comment by inghamn** [comment]
Sorting is not working correctly for any of the fields.

**Comment by charlesbrandt** [comment]
We just received another report about this issue: 

![ureport-sort](https://user-images.githubusercontent.com/2225624/52430605-7d971f00-2ad4-11e9-8645-2b0031f00828.png)

**Comment by inghamn** [comment]
It looks like part of the problem is the templating.  The links to each of the sort options are all the same; they're all rendering a link to sort by status.

**Comment by inghamn** [comment]
Boneheaded bug on my part.  I have to render the sort URLs out as as string before assigning them to be rendered.  Objects are passed by reference, so if they're not rendered out, at the end of the loop, they're strill all the same object.
