### ISSUE TITLE
New category form does not work

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#279]
While trying to create a new Category, the form stops rendering after:
SLA (Service Level Agreement)

Departments agree to handle new cases within the time specified.

Department

**Comment by inghamn** [comment]
/crm/categories/update

Call to a member function getPeople() on null

Array
(
    [timestamp] => DateTime Object
        (
            [date] => 2016-09-13 10:01:25.000000
            [timezone_type] => 3
            [timezone] => America/Indiana/Indianapolis
        )

    [priority] => 3
    [priorityName] => ERR
    [message] => Call to a member function getPeople() on null
    [extra] => Array
        (
            [file] => /srv/sites/crm/blocks/html/categories/updateCategoryForm.inc
            [line] => 89
        )

)

**Comment by inghamn** [comment]
Caused #283
