### ISSUE TITLE
Show category description on New Case page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#281]
When creating a new case and choosing a category, the category description should be shown to the right of the category select field. This will help employees know what different categories are supposed to be used for.

**Comment by charlesbrandt** [comment]
It may also make sense to solicit feedback on the category descriptions to make it more clear what they're used for. Maybe something as simple as a mailto link that sets the subject and email address (omitted here). 

Part of this gets in to coordinating with different departments on how they want to use the system.  This was brought up in our training discussions as a point of confusion, but also something that is beyond the scope of the system itself.

**Comment by inghamn** [comment]
It sounds like we need to show the descriptions for all the categories so the employee can scan the list looking for the category that would apply to their problem.  Making them choose each category, one at a time, before we show them the description doesn't seem like a nice user experience.

Are we wanting to redesign the new case form to take into account showing all this information to the employee?

**Comment by charlesbrandt** [comment]
Showing the description for the currently selected category seems better than not showing any description at all and should be a simple fix. We could explore other designs for the new case in the future, but for now let's keep it simple.
