### ISSUE TITLE
Case details location map is cut off when printing

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#288]
Printing the details of a case does not show the full map. The marker on the map is not visible which makes it difficult to use the map. 

We could explore 2 options here... 

1) make the case detail page responsive. When the width is narrow (e.g. page width or less), we could collapse the layout to a single column. In this case, address and map could show up before the case detail section, and "Other cases for this location" could move to the end of the "History" section. 

2) a custom CSS file specific for the print view. This may address the print view specifically, but 1) may help more generally.

**Comment by inghamn** [comment]
We discussed it, and for the print view, decided to also hide the header, footer, dropdown buttons, and ticketList as well.

**Comment by inghamn** [comment]
In cases where the map gets pushed down , the map gets cut off at the bottom of the page.

I think we should add CSS to always page-break-before the map.  This means our printouts will always be at least two pieces of paper.
