### ISSUE TITLE
Departmental Report on Staff Performance

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/uReport#297]
HAND is looking for a report that would look a lot like the main report table but be broken down with all HAND staff in uReport to show...

Avg Days Open, Open, Opened Today, Opened This Week, Opened This Month, Closed Today, Closed This Week, Closed This Month

Rosie Beaman would be the point person on this.

**Comment by inghamn** [comment]
The new Staff Report has been pushed to production
