### ISSUE TITLE
add a media upload option in the staff version of ureport

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/uReport#308]
uReport kept saying "fatal" error when trying citizen version. Was able to create one logged on as staff, but no picture option. Can we add a media upload option in the staff ureport application please. 

Via:
https://bloomington.in.gov/crm/tickets/view?ticket_id=160286

**Comment by inghamn** [comment]
This already exists.  Actions->Upload a Photo/File

**Comment by saderofhand** [comment]
Thanks, I see that now.  Just wasn't on the initial open a case screen unlike the web version.
