### ISSUE TITLE
Android client reports "Post failed" but issues are created on the server, resulting in duplicates

### ISSUE THREAD

**Issue by markstos** [City-of-Bloomington/uReport#314]
Today I submitted  uReport #161391 from my Android phone, but got a "Post failed" response. Assuming it didn't go through, I submitted again and got the same result of "Post Failed". On the 3rd time, it appeared to be successful. 

Now back at my desk, I see that #161392 and #161393 were also created, resulting in duplicates. 

The Android app should only report "Post Failed" if the post actually failed to avoid having the staff deal with duplicates when people reasonable attempt to re-submit failed requests.

**Comment by inghamn** [comment]
The android client is no longer maintained.  We've published a new mobile friendly web based client.  
https://bloomington.in.gov/ureport
