### ISSUE TITLE
Tickets do not display coordinates

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#319]
We never display the latitude, longitude for tickets.  This is a problem for tickets that do not have an address and only have coordinates.  Somewhere during the redesign, we stopped displaying this information.

https://bloomington.in.gov/crm/tickets/view?ticket_id=164108

**Comment by laurahaley** [comment]
They also stopped being displayed in myBloomington


Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
#350

**Comment by inghamn** [comment]
Latitude and Longitude are displayed on the view ticket screen.
