### ISSUE TITLE
header search form button

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/uReport#327]
The button is misaligned, it should stay inline horizontally with the form input.

<img width="378" alt="screen shot 2018-07-20 at 10 48 37 am" src="https://user-images.githubusercontent.com/2372040/43009091-b36ac8a2-8c0a-11e8-9282-23cde781b4c3.png">

**Comment by inghamn** [comment]
This is a city website problem.  Not a problem with uReport.
