### ISSUE TITLE
Structured submissions

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/uReport#338]
Structured form data isn't coming through for the scooter and graffiti categories.  I could be missing this though.  https://bloomington.in.gov/crm/tickets/view?ticket_id=166584

**Comment by inghamn** [comment]
These fields are not being posted by the open311-nodejs application.

https://github.com/City-of-Bloomington/open311-nodejs/issues/20

**Comment by inghamn** [comment]
The nodejs application is posting the additional attributes now
