### ISSUE TITLE
Use a no-rely return email address

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/uReport#364]
Currently the system generated email uses the string "ureport@ureport-prod.bloomington.in.gov" for the instance of ureport at the City of Bloomington.

The server name "ureport-prod.bloomington.in.gov" does not have an MX DNS record and therefore is un reply-able.

**Comment by schertza** [comment]
If the desired action of the "send email" from within ureport is to "protect" the senders email address: then we may consider the from email address to be "no-reply@bloomington.in.gov".

Also again a footer could concatenated to the body of the email explaining that the email is "non-reply-able". something like: "*** this is a system generated email. this email cannot be replied to"

**Comment by inghamn** [comment]
The from address is not controlled via configuration.

**Comment by inghamn** [comment]
Fixes #313
