### ISSUE TITLE
do i need a open311 server to use uReport?

### ISSUE THREAD

**Issue by majaz2017** [City-of-Bloomington/uReport#365]
hi all,
i'm trying to install uReport in my vps sever (and locally) but i'm having issues doing that
locally i get 
![image](https://user-images.githubusercontent.com/34025759/63221274-52863a00-c19f-11e9-8ae3-8ee711fc5ab9.png)
what could by the problem?

**Comment by inghamn** [comment]
I would check to make sure your Apache configuration is correctly set to rewrite urls to index.php.  Depending on where you've put stuff, the Apache conf would look something like this:

```apache
Alias /crm "/srv/sites/ureport/public"
<Directory "/srv/sites/ureport/public">
    Options FollowSymLinks
    AllowOverride None
    Require all granted

    RewriteEngine On
    RewriteBase /crm
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule .? /crm/index.php [NC,L]

    php_value post_max_size 10M
    php_value upload_max_filesize 10M

    SetEnv SITE_HOME /srv/data/ureport
</Directory>
```
