### ISSUE TITLE
Export shown results to CSV

### ISSUE THREAD

**Issue by chenglan1** [City-of-Bloomington/uReport#369]
Enable a button to export results from "any" list of tickets displayed (similar to "Printable results").

**Comment by inghamn** [comment]
It looks like CSV format is already implemented for search results.  We might just need to add a link to that format.

**Comment by inghamn** [comment]
The CSV templates were really old and unused.  They should have been removed long ago, to avoid confusion.  I've had to rewrite them from scratch.
