### ISSUE TITLE
Thumbnails not being generated

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/uReport#375]
An individual ticket image thumbnail is busted via an additional `/150/`

**eg.** https://bloomington.in.gov/crm/tickets/view?ticket_id=172215

<img width="811" alt="Screen Shot 2020-04-13 at 10 18 08 AM" src="https://user-images.githubusercontent.com/2372040/79127500-014f3a00-7d70-11ea-86d6-561195930908.png">

https://github.com/City-of-Bloomington/uReport/blob/f951c575489ceb499c5d2e1dfdf1d48ac83eb12e/crm/blocks/html/media/thumbnail.inc#L26-L28

img src: https://bloomington.in.gov/crm/media/2020/4/12/150/5e93954e1eef6

correct src (as seen on the a href): https://bloomington.in.gov/crm/media/2020/4/12/5e93954e1eef6

**Comment by inghamn** [comment]
The new apache configuration doesn't send thumbnail requests to PHP.  I forgot to take that aspect into account when I replaced the symlink with the Apache config.
