### ISSUE TITLE
Export data to CKAN

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/uReport#66]

**Comment by inghamn** [comment]
I can't remember what this was intended to do.

**Comment by rbdietz** [comment]
Allows the data of a query such as "List all open Potholes" to be included in CKAN.  We need to do this or something like it to get our open311 data into our data portal.  Needs to be done.  If not this way then some other.

**Comment by inghamn** [comment]
Andrew Nicklen recently posted about a standard format for bulk export of Open311 data.  We should probably try to match the fields he's recommending:

http://govex.jhu.edu/untangling-311-request-data/

**Comment by inghamn** [comment]
Same as #237

**Comment by inghamn** [comment]
We need a way to integrate with CKAN.

We need a way to define multiple queries that produce CSV output, along with the CKAN dataset resource ID, username, and password to upload the CSV file into.  We'll need to sort out the authentication to CKAN's web service APIs.

uReport will need a cron system to periodically run all of these exports, save the CSV output as a file, connect to CKAN, and upload the fresh CSV file into a dataset resource that uReport knows about.

**Comment by inghamn** [comment]
We talked about it, and decided to build a CSV output format for the ticket search route.

**Comment by rbdietz** [comment]
Is this present in the data portal now?
