### ISSUE TITLE
When changing a category, the old fields need to be preserved

### ISSUE THREAD

**Issue by autrice** [City-of-Bloomington/uReport#89]
This was the case, I'm not sure when it changed. here were my old images when I was explaining to people how this worked.
![same_field](https://f.cloud.github.com/assets/418093/432281/e88b45f0-ae9f-11e2-91ad-0af54a65d43d.jpg)
![history_change](https://f.cloud.github.com/assets/418093/432284/ee198c7a-ae9f-11e2-9181-e65f4c8a820d.jpg)

**Comment by inghamn** [comment]
This can be resolved by implementing #240

**Comment by inghamn** [comment]
We now preserve the old information on a ticket when there's a change.
